# -*- coding: utf-8 -*-
"""milestone_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W7gnWZXfqIyA-QND6EoBNHu53NW65HoS

User enters topic
        ↓
API key is loaded
        ↓
Recent papers are searched
        ↓
Results are filtered by year
        ↓
Metadata is extracted
        ↓
Results saved as JSON
        ↓
Top papers displayed
        ↓
PDF downloaded and saved locally
"""

# ============================================
#  Topic Input & Paper Search
# ============================================
#INSTALL REQUIRING LAIBRARIES

!pip install semanticscholar python-dotenv requests -q

import json
import os
from datetime import datetime
from semanticscholar import SemanticScholar
from dotenv import load_dotenv

# ==========================
# 1. SETUP API KEY
# ==========================

def setup_api_key():
    """Loads Semantic Scholar API key from .env or creates file if missing."""

    load_dotenv()
    API_KEY = os.getenv("SEMANTIC_SCHOLAR_API_KEY")

    # If .env not present → create one
    if not API_KEY:
        with open(".env", "w") as f:
            f.write("SEMANTIC_SCHOLAR_API_KEY=LIh1hqt2wg8fh3a1q4ooK2ltZS5lJePH5Ydb66ew\n")
        load_dotenv()
        API_KEY = os.getenv("SEMANTIC_SCHOLAR_API_KEY")

    # Initialize Semantic Scholar client
    if API_KEY:
        sch = SemanticScholar(api_key=API_KEY)
        print(" Semantic Scholar initialized WITH API key.")
    else:
        sch = SemanticScholar()
        print(" Initialized WITHOUT API key (limited usage).")

    return sch



# ==========================
# 2. SEARCH RECENT PAPERS
# ==========================

def search_recent_papers(topic, years=2, limit=20):
    """
    Search for recent papers (last X years) on a topic.
    Returns structured dictionary of results.
    """

    print(f"\n Searching recent papers for topic: '{topic}'")
    print(f"   Limiting to last {years} years")

    sch = setup_api_key()
    current_year = datetime.now().year
    min_year = current_year - years

    try:
        # Search papers
        results = sch.search_paper(
            query=topic,
            limit=limit,
            fields=[
                "paperId", "title", "abstract", "year", "authors",
                "citationCount", "openAccessPdf", "url", "venue"
            ]
        )

        papers = []
        for paper in results:
            if paper.year and paper.year >= min_year:
                papers.append({
                    "title": paper.title,
                    "authors": [a["name"] for a in paper.authors] if paper.authors else [],
                    "year": paper.year,
                    "paperId": paper.paperId,
                    "abstract": (paper.abstract[:300] + "...")
                        if paper.abstract else "No abstract available",
                    "citationCount": paper.citationCount,
                    "venue": paper.venue if hasattr(paper, "venue") else None,
                    "url": paper.url,
                    "pdf_url": paper.openAccessPdf["url"] if paper.openAccessPdf else None,
                    "has_pdf": bool(paper.openAccessPdf)
                })

        pdf_count = sum(1 for p in papers if p["has_pdf"])

        print("\n Search complete!")
        print(f"   Total recent papers: {len(papers)}")
        print(f"   PDFs available: {pdf_count}")

        return {
            "topic": topic,
            "search_timestamp": datetime.now().isoformat(),
            "years_considered": years,
            "total_results": len(papers),
            "papers_with_pdf": pdf_count,
            "papers": papers
        }

    except Exception as e:
        print(f" ERROR: Could not fetch papers → {e}")
        return None



# ==========================
# 3. SAVE RESULTS AS JSON
# ==========================

def save_recent_results(data, filename=None):
    """Save recent paper search results into data/search_results folder."""

    if not filename:
        safe_topic = "".join(c for c in data["topic"] if c.isalnum() or c == " ").replace(" ", "_")
        filename = f"recent_papers_{safe_topic}.json"

    os.makedirs("data/search_results", exist_ok=True)
    filepath = os.path.join("data/search_results", filename)

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4, ensure_ascii=False)

    print(f" Results saved to: {filepath}")
    return filepath



# ==========================
# 4. DISPLAY RECENT PAPERS
# ==========================

def display_recent_results(data, max_display=10):
    """Pretty print top recent papers."""

    print(f"\n--- Top {max_display} Recent Papers for '{data['topic']}' ---")

    for i, paper in enumerate(data["papers"][:max_display]):
        print(f"\n{i+1}. Title: {paper['title']}")
        print(f"   Authors: {', '.join(paper['authors'])}")
        print(f"   Year: {paper['year']}")
        print(f"   Citations: {paper['citationCount']}")
        print(f"   Venue: {paper['venue']}")
        print(f"   Abstract: {paper['abstract']}")
        print(f"   URL: {paper['url']}")
        print(f"   PDF Available: {paper['has_pdf']}")

def display_recent_results(data, max_display=10):
    """Pretty print top recent papers in clean format."""

    print(f"\n--- Top {max_display} Recent Papers for '{data['topic']}' ---")

    for i, paper in enumerate(data["papers"][:max_display]):
        print(f"\n{i+1}. Title: {paper['title']}")
        print(f"   Authors: {', '.join(paper['authors']) if paper['authors'] else 'Unknown'}")
        print(f"   Year: {paper['year']}")
        print(f"   Citations: {paper['citationCount']}")
        print(f"   Venue: {paper['venue'] if paper['venue'] else 'Not available'}")
        print(f"   Abstract: {paper['abstract']}")
        print(f"   URL: {paper['url']}")
        print(f"   PDF Available: {paper['has_pdf']}")

data = search_recent_papers("Quantum Computing", years=3, limit=25)
display_recent_results(data)
save_recent_results(data)

def user_download_one_pdf(data):
    """Allows the user to select and download one PDF from the search results."""

    papers_with_pdf = [p for p in data["papers"] if p["has_pdf"]]

    if not papers_with_pdf:
        print("No papers with downloadable PDFs found in the current results.")
        return

    print("\n--- Papers with Available PDFs ---")
    for i, paper in enumerate(papers_with_pdf):
        print(f"{i+1}. {paper['title']} (Year: {paper['year']})")

    while True:
        try:
            choice = input("Enter the number of the PDF to download (or 'q' to quit): ")
            if choice.lower() == 'q':
                print("Exiting PDF download.")
                return

            idx = int(choice) - 1
            if 0 <= idx < len(papers_with_pdf):
                selected_paper = papers_with_pdf[idx]
                download_pdf(selected_paper["pdf_url"], selected_paper["title"])
                return
            else:
                print("Invalid number. Please try again.")
        except ValueError:
            print("Invalid input. Please enter a number or 'q'.")



import requests
import os

def download_pdf(pdf_url, title):
    """Downloads a PDF from a given URL and saves it to the 'downloaded_pdfs' directory."""
    if not pdf_url:
        print(f"No PDF URL available for '{title}'. Skipping download.")
        return

    # Sanitize title for filename
    safe_title = "".join(c for c in title if c.isalnum() or c in (' ', '.', '_')).rstrip()
    safe_title = safe_title.replace(" ", "_")
    filename = f"{safe_title}.pdf"
    filepath = os.path.join("downloaded_pdfs", filename)

    os.makedirs("downloaded_pdfs", exist_ok=True)

    print(f"Attempting to download '{title}' from {pdf_url}...")
    try:
        response = requests.get(pdf_url, stream=True)
        response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)

        with open(filepath, "wb") as pdf_file:
            for chunk in response.iter_content(chunk_size=8192):
                pdf_file.write(chunk)
        print(f"Successfully downloaded and saved: {filepath}")
        return filepath
    except requests.exceptions.RequestException as e:
        print(f"Error downloading PDF '{title}' from '{pdf_url}': {e}")
        return None

data = search_recent_papers("Quntum Computing", years=3, limit=25)
display_recent_results(data)
user_download_one_pdf(data)

"""implementation of the text extraction module for parsing downloaded research paper PDFs

## Install Libraries and Setup Directories
"""

import os


!pip install PyMuPDF sentence-transformers -q

dirs_to_create = [
    "downloaded_pdfs",
    "data/extracted_text",
    "data/structured_sections",
    "data/comparisons"
]

for d in dirs_to_create:
    os.makedirs(d, exist_ok=True)
    print(f"Ensured directory exists: {d}")

"""## Extract Raw Text from PDFs"""

import fitz  # PyMuPDF
import os

def extract_text_from_pdf(pdf_path, output_dir):
    """
    Extracts raw text content from a PDF file, sanitizes it, and saves it as a .txt file.
    """
    try:
        document = fitz.open(pdf_path)
        full_text = []
        for page_num in range(len(document)):
            page = document.load_page(page_num)
            full_text.append(page.get_text())
        document.close()

        # Sanitize the extracted text
        cleaned_text = "\n".join(full_text)
        cleaned_text = os.linesep.join([s for s in cleaned_text.splitlines() if s.strip()]) # Remove empty lines
        cleaned_text = cleaned_text.strip()

        # Construct output filename
        pdf_filename = os.path.basename(pdf_path)
        txt_filename = os.path.splitext(pdf_filename)[0] + ".txt"
        output_filepath = os.path.join(output_dir, txt_filename)

        with open(output_filepath, "w", encoding="utf-8") as f:
            f.write(cleaned_text)
        print(f"Extracted text from '{pdf_filename}' to '{output_filepath}'")
        return output_filepath

    except Exception as e:
        print(f"Error extracting text from '{pdf_path}': {e}")
        return None

# Define input and output directories
input_pdf_dir = "downloaded_pdfs"
output_text_dir = "data/extracted_text"

# Ensure output directory exists (already done in previous step, but good practice)
os.makedirs(output_text_dir, exist_ok=True)

# Iterate through all .pdf files in the input directory
pdf_files = [f for f in os.listdir(input_pdf_dir) if f.lower().endswith('.pdf')]

if not pdf_files:
    print(f"No PDF files found in '{input_pdf_dir}'. Please ensure PDFs are present.")
else:
    print(f"Found {len(pdf_files)} PDF files. Starting text extraction...")
    for pdf_file in pdf_files:
        full_pdf_path = os.path.join(input_pdf_dir, pdf_file)
        extract_text_from_pdf(full_pdf_path, output_text_dir)

print("Text extraction process complete.")

"""## Clean and Structure Extracted Text

"""

import os
import re
import json

def structure_text_content(text_filepath, output_dir):
    """
    Reads a raw text file, extracts specific sections (Abstract, Introduction, Conclusion),
    cleans them, and saves the structured content as a JSON file.
    """
    try:
        with open(text_filepath, "r", encoding="utf-8") as f:
            full_text = f.read()

        structured_data = {
            "full_text_path": text_filepath,
            "abstract": "",
            "introduction": "",
            "conclusion": ""
        }

        # Regex patterns for common sections (case-insensitive and handling variations)
        # Abstract: usually at the beginning
        abstract_match = re.search(r"(?i)abstract\n\s*(.*?)(?=\n\s*1\s*introduction|\n\s*i\s*introduction|\n\s*keywords|\n\s*[a-z])", full_text, re.DOTALL)
        if abstract_match:
            structured_data["abstract"] = re.sub(r'\s+', ' ', abstract_match.group(1).strip())

        # Introduction: often numbered or clearly headed
        introduction_match = re.search(r"(?i)(?:1\s*|i\s*|)\s*introduction\n\s*(.*?)(?=\n\s*(?:2\s*|ii\s*|)\s*(?:related work|background|methodology)|\n\s*(?:conclusion|abstract|references)|\n\s*[a-z])", full_text, re.DOTALL)
        if introduction_match:
            structured_data["introduction"] = re.sub(r'\s+', ' ', introduction_match.group(1).strip())

        # Conclusion: usually at the end, often numbered
        conclusion_match = re.search(r"(?i)(?:\n\s*(?:\d+\s*|x*i*v*\s*|)\s*conclusion(?:s?)|\n\s*discussion and conclusion(?:s?))\n\s*(.*?)(?=\n\s*(?:acknowledgements|references|appendix|copyright|further work)|$)", full_text, re.DOTALL)
        if conclusion_match:
            structured_data["conclusion"] = re.sub(r'\s+', ' ', conclusion_match.group(1).strip())

        # Construct output filename
        text_filename = os.path.basename(text_filepath)
        json_filename = os.path.splitext(text_filename)[0] + ".json"
        output_filepath = os.path.join(output_dir, json_filename)

        with open(output_filepath, "w", encoding="utf-8") as f:
            json.dump(structured_data, f, indent=4, ensure_ascii=False)
        print(f"Structured content from '{text_filename}' saved to '{output_filepath}'")
        return output_filepath

    except Exception as e:
        print(f"Error structuring content from '{text_filepath}': {e}")
        return None

# Define input and output directories
input_text_dir = "data/extracted_text"
output_structured_dir = "data/structured_sections"

# Ensure output directory exists
os.makedirs(output_structured_dir, exist_ok=True)

# Iterate through all .txt files in the input directory
txt_files = [f for f in os.listdir(input_text_dir) if f.lower().endswith('.txt')]

if not txt_files:
    print(f"No text files found in '{input_text_dir}'. Please ensure text files are present.")
else:
    print(f"Found {len(txt_files)} text files. Starting content structuring...")
    for txt_file in txt_files:
        full_text_path = os.path.join(input_text_dir, txt_file)
        structure_text_content(full_text_path, output_structured_dir)

print("Content structuring process complete.")

import os
import json
import re
import nltk

# Ensure nltk punkt tokenizer is available
try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt', quiet=True)

# Also explicitly download 'punkt_tab' if it's the one causing issues, as suggested by the error
try:
    nltk.data.find('tokenizers/punkt_tab')
except LookupError:
    nltk.download('punkt_tab', quiet=True)

def extract_key_findings(structured_data_filepath, output_dir, num_sentences=2):
    """
    Loads structured content, extracts key findings from 'abstract', 'introduction', and 'conclusion',
    and saves the updated content as a JSON file.
    """
    try:
        with open(structured_data_filepath, "r", encoding="utf-8") as f:
            structured_data = json.load(f)

        key_findings = {}

        # Helper function to extract N sentences
        def get_key_sentences(text, n):
            if not text or len(text.strip()) < 10: # Handle empty or very short sections
                return "No key findings available for this section."
            sentences = nltk.sent_tokenize(text)
            return " ".join(sentences[:n]).strip()

        # Extract key findings from each section
        key_findings["abstract"] = get_key_sentences(structured_data.get("abstract", ""), num_sentences)
        # For introduction, sometimes the last sentences are more indicative of the paper's contribution
        intro_text = structured_data.get("introduction", "")
        if intro_text and len(nltk.sent_tokenize(intro_text)) > num_sentences:
            sentences = nltk.sent_tokenize(intro_text)
            key_findings["introduction"] = " ".join(sentences[-num_sentences:]).strip()
        else:
            key_findings["introduction"] = get_key_sentences(intro_text, num_sentences)

        key_findings["conclusion"] = get_key_sentences(structured_data.get("conclusion", ""), num_sentences)

        structured_data["key_findings"] = key_findings

        # Construct output filename (overwrite the original structured JSON)
        json_filename = os.path.basename(structured_data_filepath)
        output_filepath = os.path.join(output_dir, json_filename)

        with open(output_filepath, "w", encoding="utf-8") as f:
            json.dump(structured_data, f, indent=4, ensure_ascii=False)
        print(f"Extracted key findings and saved to '{output_filepath}'")
        return output_filepath

    except Exception as e:
        print(f"Error extracting key findings from '{structured_data_filepath}': {e}")
        return None

# Define input and output directories
input_structured_dir = "data/structured_sections"
output_key_findings_dir = "data/structured_sections" # Overwriting original structured JSONs

# Iterate through all .json files in the input directory
json_files = [f for f in os.listdir(input_structured_dir) if f.lower().endswith('.json')]

if not json_files:
    print(f"No JSON files found in '{input_structured_dir}'. Please ensure structured JSONs are present.")
else:
    print(f"Found {len(json_files)} structured JSON files. Starting key findings extraction...")
    for json_file in json_files:
        full_json_path = os.path.join(input_structured_dir, json_file)
        extract_key_findings(full_json_path, output_key_findings_dir)

print("Key findings extraction process complete.")

import os
import json
import re
import nltk

# Ensure nltk punkt tokenizer is available
try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt', quiet=True)

# Also explicitly download 'punkt_tab' if it's the one causing issues, as suggested by the error
try:
    nltk.data.find('tokenizers/punkt_tab')
except LookupError:
    nltk.download('punkt_tab', quiet=True)

def extract_key_findings(structured_data_filepath, output_dir, num_sentences=2):
    """
    Loads structured content, extracts key findings from 'abstract', 'introduction', and 'conclusion',
    and saves the updated content as a JSON file.
    """
    try:
        with open(structured_data_filepath, "r", encoding="utf-8") as f:
            structured_data = json.load(f)

        key_findings = {}

        # Helper function to extract N sentences
        def get_key_sentences(text, n):
            if not text or len(text.strip()) < 10: # Handle empty or very short sections
                return "No key findings available for this section."
            sentences = nltk.sent_tokenize(text)
            return " ".join(sentences[:n]).strip()

        # Extract key findings from each section
        key_findings["abstract"] = get_key_sentences(structured_data.get("abstract", ""), num_sentences)
        # For introduction, sometimes the last sentences are more indicative of the paper's contribution
        intro_text = structured_data.get("introduction", "")
        if intro_text and len(nltk.sent_tokenize(intro_text)) > num_sentences:
            sentences = nltk.sent_tokenize(intro_text)
            key_findings["introduction"] = " ".join(sentences[-num_sentences:]).strip()
        else:
            key_findings["introduction"] = get_key_sentences(intro_text, num_sentences)

        key_findings["conclusion"] = get_key_sentences(structured_data.get("conclusion", ""), num_sentences)

        structured_data["key_findings"] = key_findings

        # Construct output filename (overwrite the original structured JSON)
        json_filename = os.path.basename(structured_data_filepath)
        output_filepath = os.path.join(output_dir, json_filename)

        with open(output_filepath, "w", encoding="utf-8") as f:
            json.dump(structured_data, f, indent=4, ensure_ascii=False)
        print(f"Extracted key findings and saved to '{output_filepath}'")
        return output_filepath

    except Exception as e:
        print(f"Error extracting key findings from '{structured_data_filepath}': {e}")
        return None

# Define input and output directories
input_structured_dir = "data/structured_sections"
output_key_findings_dir = "data/structured_sections" # Overwriting original structured JSONs

# Iterate through all .json files in the input directory
json_files = [f for f in os.listdir(input_structured_dir) if f.lower().endswith('.json')]

if not json_files:
    print(f"No JSON files found in '{input_structured_dir}'. Please ensure structured JSONs are present.")
else:
    print(f"Found {len(json_files)} structured JSON files. Starting key findings extraction...")
    for json_file in json_files:
        full_json_path = os.path.join(input_structured_dir, json_file)
        extract_key_findings(full_json_path, output_key_findings_dir)

print("Key findings extraction process complete.")

"""## Compare Key Findings Across Papers"""

import os
import json
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# 1. Load Sentence Transformer Model
print("Loading Sentence Transformer model...")
model = SentenceTransformer('all-MiniLM-L6-v2')
print("Sentence Transformer model loaded.")

# 2. Load All Key Findings
input_structured_dir = "data/structured_sections"

papers_data = []
json_files = [f for f in os.listdir(input_structured_dir) if f.lower().endswith('.json')]

if not json_files:
    print(f"No JSON files found in '{input_structured_dir}'. Cannot perform comparison.")
else:
    print(f"Found {len(json_files)} structured JSON files for comparison.")
    for json_file in json_files:
        full_json_path = os.path.join(input_structured_dir, json_file)
        try:
            with open(full_json_path, "r", encoding="utf-8") as f:
                data = json.load(f)

            title = os.path.splitext(json_file)[0].replace("_", " ") # Derive title from filename
            key_findings_sections = data.get("key_findings", {})

            combined_key_findings = []
            if key_findings_sections.get("abstract"): combined_key_findings.append(key_findings_sections["abstract"])
            if key_findings_sections.get("introduction"): combined_key_findings.append(key_findings_sections["introduction"])
            if key_findings_sections.get("conclusion"): combined_key_findings.append(key_findings_sections["conclusion"])

            full_key_findings_text = " ".join(combined_key_findings).strip()

            if full_key_findings_text:
                papers_data.append({
                    "title": title,
                    "text": full_key_findings_text,
                    "filepath": full_json_path
                })
            else:
                print(f"Warning: No key findings found for '{title}', skipping.")
        except Exception as e:
            print(f"Error loading or processing '{json_file}': {e}")

    if not papers_data:
        print("No papers with valid key findings to compare.")
    else:
        # 3. Generate Embeddings
        print(f"Generating embeddings for {len(papers_data)} papers...")
        corpus_sentences = [p["text"] for p in papers_data]
        corpus_embeddings = model.encode(corpus_sentences, convert_to_tensor=True)
        print("Embeddings generated.")

        # 4. Calculate Similarity
        print("Calculating cosine similarity...")
        cosine_scores = cosine_similarity(corpus_embeddings)
        print("Cosine similarity calculated.")

        # 5. Structure Comparison Results
        comparison_results = []
        for i in range(len(papers_data)):
            for j in range(i + 1, len(papers_data)): # Avoid self-comparison and duplicate pairs
                similarity = cosine_scores[i][j]
                comparison_results.append({
                    "paper1_title": papers_data[i]["title"],
                    "paper2_title": papers_data[j]["title"],
                    "similarity_score": float(similarity) # Convert to float for JSON serialization
                })

        # Sort by similarity score in descending order
        comparison_results_sorted = sorted(comparison_results, key=lambda x: x["similarity_score"], reverse=True)

        # 6. Save Comparison Results
        output_comparisons_dir = "data/comparisons"
        os.makedirs(output_comparisons_dir, exist_ok=True)
        output_filepath = os.path.join(output_comparisons_dir, "comparison_results.json")

        with open(output_filepath, "w", encoding="utf-8") as f:
            json.dump(comparison_results_sorted, f, indent=4, ensure_ascii=False)
        print(f"Comparison results saved to: {output_filepath}")

        # 7. Provide a Summary/Example
        print("\n--- Top 5 Most Similar Paper Pairs ---")
        for i, result in enumerate(comparison_results_sorted[:5]):
            print(f"{i+1}. \"" + result["paper1_title"] + "\" vs \"" + result["paper2_title"] + f"\" (Similarity: {result["similarity_score"]:.4f})")

import os
import re
import json

def structure_text_content(text_filepath, output_dir):
    """
    Reads a raw text file, extracts specific sections (Abstract, Introduction, Conclusion),
    cleans them, and saves the structured content as a JSON file.
    """
    try:
        with open(text_filepath, "r", encoding="utf-8") as f:
            full_text = f.read()

        structured_data = {
            "full_text_path": text_filepath,
            "abstract": "",
            "introduction": "",
            "conclusion": ""
        }

        # Regex patterns for common sections (case-insensitive and handling variations)
        # Abstract: usually at the beginning, often separated by newlines
        abstract_match = re.search(
            r"(?i)abstract\s*(?:\n|\r|\r\n)(.*?)(?=\n\s*(?:(?:1|i)\s*introduction|keywords|i\s*introduction|ii\s*related work|1\s*introduction|section|introduction:)|$)",
            full_text, re.DOTALL
        )
        if abstract_match:
            structured_data["abstract"] = re.sub(r'\s+', ' ', abstract_match.group(1).strip())

        # Introduction: often numbered or clearly headed, capture until next major section
        introduction_match = re.search(
            r"(?i)(?:^|\n)\s*(?:(?:1|i)\s*|)\s*introduction(?:\s*\:|)\s*(?:\n|\r|\r\n)(.*?)(?=\n\s*(?:(?:2|ii)\s*|\d+\s*\.)(?:related work|background|methodology|literature review|section|materials and methods|experiment|proposed method)|(?:\n\s*conclusion(?:s?))|(?=\n\s*(?:acknowledgements|references|appendix))|$)",
            full_text, re.DOTALL
        )
        if introduction_match:
            structured_data["introduction"] = re.sub(r'\s+', ' ', introduction_match.group(1).strip())

        # Conclusion: usually at the end, often numbered, capture until acknowledgements/references or end
        conclusion_match = re.search(
            r"(?i)(?:^|\n)\s*(?:\d+\s*|x*i*v*\s*|)\s*conclusion(?:s?)(?:\s+and\s+discussion)?\s*(?:\n|\r|\r\n)(.*?)(?=\n\s*(?:acknowledgements|references|appendix|copyright|further work)|$)",
            full_text, re.DOTALL
        )
        if conclusion_match:
            structured_data["conclusion"] = re.sub(r'\s+', ' ', conclusion_match.group(1).strip())

        # Construct output filename
        text_filename = os.path.basename(text_filepath)
        json_filename = os.path.splitext(text_filename)[0] + ".json"
        output_filepath = os.path.join(output_dir, json_filename)

        with open(output_filepath, "w", encoding="utf-8") as f:
            json.dump(structured_data, f, indent=4, ensure_ascii=False)
        print(f"Structured content from '{text_filename}' saved to '{output_filepath}'")
        return output_filepath

    except Exception as e:
        print(f"Error structuring content from '{text_filepath}': {e}")
        return None

# Define input and output directories
input_text_dir = "data/extracted_text"
output_structured_dir = "data/structured_sections"

# Ensure output directory exists (already done in previous step, but good practice)
os.makedirs(output_structured_dir, exist_ok=True)

# Iterate through all .txt files in the input directory
txt_files = [f for f in os.listdir(input_text_dir) if f.lower().endswith('.txt')]

if not txt_files:
    print(f"No text files found in '{input_text_dir}'. Please ensure text files are present.")
else:
    print(f"Found {len(txt_files)} text files. Starting content structuring...")
    for txt_file in txt_files:
        full_text_path = os.path.join(input_text_dir, txt_file)
        structure_text_content(full_text_path, output_structured_dir)

print("Content structuring process complete.")

import os
import json
import re
import nltk

# Ensure nltk punkt tokenizer is available
try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt', quiet=True)

# Also explicitly download 'punkt_tab' if it's the one causing issues, as suggested by the error
try:
    nltk.data.find('tokenizers/punkt_tab')
except LookupError:
    nltk.download('punkt_tab', quiet=True)

def extract_key_findings(structured_data_filepath, output_dir, num_sentences=2):
    """
    Loads structured content, extracts key findings from 'abstract', 'introduction', and 'conclusion',
    and saves the updated content as a JSON file.
    """
    try:
        with open(structured_data_filepath, "r", encoding="utf-8") as f:
            structured_data = json.load(f)

        key_findings = {}

        # Helper function to extract N sentences
        def get_key_sentences(text, n):
            if not text or len(text.strip()) < 10: # Handle empty or very short sections
                return "No key findings available for this section."
            sentences = nltk.sent_tokenize(text)
            return " ".join(sentences[:n]).strip()

        # Extract key findings from each section
        key_findings["abstract"] = get_key_sentences(structured_data.get("abstract", ""), num_sentences)
        # For introduction, sometimes the last sentences are more indicative of the paper's contribution
        intro_text = structured_data.get("introduction", "")
        if intro_text and len(nltk.sent_tokenize(intro_text)) > num_sentences:
            sentences = nltk.sent_tokenize(intro_text)
            key_findings["introduction"] = " ".join(sentences[-num_sentences:]).strip()
        else:
            key_findings["introduction"] = get_key_sentences(intro_text, num_sentences)

        key_findings["conclusion"] = get_key_sentences(structured_data.get("conclusion", ""), num_sentences)

        structured_data["key_findings"] = key_findings

        # Construct output filename (overwrite the original structured JSON)
        json_filename = os.path.basename(structured_data_filepath)
        output_filepath = os.path.join(output_dir, json_filename)

        with open(output_filepath, "w", encoding="utf-8") as f:
            json.dump(structured_data, f, indent=4, ensure_ascii=False)
        print(f"Extracted key findings and saved to '{output_filepath}'")
        return output_filepath

    except Exception as e:
        print(f"Error extracting key findings from '{structured_data_filepath}': {e}")
        return None

# Define input and output directories
input_structured_dir = "data/structured_sections"
output_key_findings_dir = "data/structured_sections" # Overwriting original structured JSONs

# Iterate through all .json files in the input directory
json_files = [f for f in os.listdir(input_structured_dir) if f.lower().endswith('.json')]

if not json_files:
    print(f"No JSON files found in '{input_structured_dir}'. Please ensure structured JSONs are present.")
else:
    print(f"Found {len(json_files)} structured JSON files. Starting key findings extraction...")
    for json_file in json_files:
        full_json_path = os.path.join(input_structured_dir, json_file)
        extract_key_findings(full_json_path, output_key_findings_dir)

print("Key findings extraction process complete.")

import os
import json
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# 1. Load Sentence Transformer Model
print("Loading Sentence Transformer model...")
model = SentenceTransformer('all-MiniLM-L6-v2')
print("Sentence Transformer model loaded.")

# 2. Load All Key Findings
input_structured_dir = "data/structured_sections"

papers_data = []
json_files = [f for f in os.listdir(input_structured_dir) if f.lower().endswith('.json')]

if not json_files:
    print(f"No JSON files found in '{input_structured_dir}'. Cannot perform comparison.")
else:
    print(f"Found {len(json_files)} structured JSON files for comparison.")
    for json_file in json_files:
        full_json_path = os.path.join(input_structured_dir, json_file)
        try:
            with open(full_json_path, "r", encoding="utf-8") as f:
                data = json.load(f)

            title = os.path.splitext(json_file)[0].replace("_", " ") # Derive title from filename
            key_findings_sections = data.get("key_findings", {})

            combined_key_findings = []
            if key_findings_sections.get("abstract"): combined_key_findings.append(key_findings_sections["abstract"])
            if key_findings_sections.get("introduction"): combined_key_findings.append(key_findings_sections["introduction"])
            if key_findings_sections.get("conclusion"): combined_key_findings.append(key_findings_sections["conclusion"])

            full_key_findings_text = " ".join(combined_key_findings).strip()

            if full_key_findings_text:
                papers_data.append({
                    "title": title,
                    "text": full_key_findings_text,
                    "filepath": full_json_path
                })
            else:
                print(f"Warning: No key findings found for '{title}', skipping.")
        except Exception as e:
            print(f"Error loading or processing '{json_file}': {e}")

    if not papers_data:
        print("No papers with valid key findings to compare.")
    else:
        # 3. Generate Embeddings
        print(f"Generating embeddings for {len(papers_data)} papers...")
        corpus_sentences = [p["text"] for p in papers_data]
        corpus_embeddings = model.encode(corpus_sentences, convert_to_tensor=True)
        print("Embeddings generated.")

        # 4. Calculate Similarity
        print("Calculating cosine similarity...")
        cosine_scores = cosine_similarity(corpus_embeddings)
        print("Cosine similarity calculated.")

        # 5. Structure Comparison Results
        comparison_results = []
        for i in range(len(papers_data)):
            for j in range(i + 1, len(papers_data)): # Avoid self-comparison and duplicate pairs
                similarity = cosine_scores[i][j]
                comparison_results.append({
                    "paper1_title": papers_data[i]["title"],
                    "paper2_title": papers_data[j]["title"],
                    "similarity_score": float(similarity) # Convert to float for JSON serialization
                })

        # Sort by similarity score in descending order
        comparison_results_sorted = sorted(comparison_results, key=lambda x: x["similarity_score"], reverse=True)

        # 6. Save Comparison Results
        output_comparisons_dir = "data/comparisons"
        os.makedirs(output_comparisons_dir, exist_ok=True)
        output_filepath = os.path.join(output_comparisons_dir, "comparison_results.json")

        with open(output_filepath, "w", encoding="utf-8") as f:
            json.dump(comparison_results_sorted, f, indent=4, ensure_ascii=False)
        print(f"Comparison results saved to: {output_filepath}")

        # 7. Provide a Summary/Example
        print("\n--- Top 5 Most Similar Paper Pairs ---")
        for i, result in enumerate(comparison_results_sorted[:5]):
            print(f"{i+1}. \"" + result["paper1_title"] + "\" vs \"" + result["paper2_title"] + f"\" (Similarity: {result["similarity_score"]:.4f})")

import os
import re
import json

def structure_text_content(text_filepath, output_dir):
    """
    Reads a raw text file, extracts specific sections (Abstract, Introduction, Conclusion),
    cleans them, and saves the structured content as a JSON file.
    """
    try:
        with open(text_filepath, "r", encoding="utf-8") as f:
            full_text = f.read()

        structured_data = {
            "full_text_path": text_filepath,
            "abstract": "",
            "introduction": "",
            "conclusion": ""
        }

        # Regex patterns for common sections (case-insensitive and handling variations)
        # Abstract: usually at the beginning, often separated by newlines
        abstract_match = re.search(
            r"(?i)abstract\s*(?:\n|\r|\r\n)(.*?)(?=\n\s*(?:(?:1|i)\s*introduction|keywords|i\s*introduction|ii\s*related work|1\s*introduction|section|introduction:)|$)",
            full_text, re.DOTALL
        )
        if abstract_match:
            structured_data["abstract"] = re.sub(r'\s+', ' ', abstract_match.group(1).strip())

        # Introduction: often numbered or clearly headed, capture until next major section
        introduction_match = re.search(
            r"(?i)(?:^|\n)\s*(?:(?:1|i)\s*|)\s*introduction(?:\s*\:|)\s*(?:\n|\r|\r\n)(.*?)(?=\n\s*(?:(?:2|ii)\s*|\d+\s*\.)(?:related work|background|methodology|literature review|section|materials and methods|experiment|proposed method)|(?:\n\s*conclusion(?:s?))|(?=\n\s*(?:acknowledgements|references|appendix))|$)",
            full_text, re.DOTALL
        )
        if introduction_match:
            structured_data["introduction"] = re.sub(r'\s+', ' ', introduction_match.group(1).strip())

        # Conclusion: usually at the end, often numbered, capture until acknowledgements/references or end
        conclusion_match = re.search(
            r"(?i)(?:^|\n)\s*(?:\d+\s*|x*i*v*\s*|)\s*conclusion(?:s?)(?:\s+and\s+discussion)?\s*(?:\n|\r|\r\n)(.*?)(?=\n\s*(?:acknowledgements|references|appendix|copyright|further work)|$)",
            full_text, re.DOTALL
        )
        if conclusion_match:
            structured_data["conclusion"] = re.sub(r'\s+', ' ', conclusion_match.group(1).strip())

        # Construct output filename
        text_filename = os.path.basename(text_filepath)
        json_filename = os.path.splitext(text_filename)[0] + ".json"
        output_filepath = os.path.join(output_dir, json_filename)

        with open(output_filepath, "w", encoding="utf-8") as f:
            json.dump(structured_data, f, indent=4, ensure_ascii=False)
        print(f"Structured content from '{text_filename}' saved to '{output_filepath}'")
        return output_filepath

    except Exception as e:
        print(f"Error structuring content from '{text_filepath}': {e}")
        return None

# Define input and output directories
input_text_dir = "data/extracted_text"
output_structured_dir = "data/structured_sections"

# Ensure output directory exists (already done in previous step, but good practice)
os.makedirs(output_structured_dir, exist_ok=True)

# Iterate through all .txt files in the input directory
txt_files = [f for f in os.listdir(input_text_dir) if f.lower().endswith('.txt')]

if not txt_files:
    print(f"No text files found in '{input_text_dir}'. Please ensure text files are present.")
else:
    print(f"Found {len(txt_files)} text files. Starting content structuring...")
    for txt_file in txt_files:
        full_text_path = os.path.join(input_text_dir, txt_file)
        structure_text_content(full_text_path, output_structured_dir)

print("Content structuring process complete.")

import os
import json
import re


all_papers_data = []


input_structured_dir = "data/structured_sections"


output_comparisons_dir = "data/comparisons"
os.makedirs(output_comparisons_dir, exist_ok=True)

json_files = [f for f in os.listdir(input_structured_dir) if f.lower().endswith('.json')]

if not json_files:
    print(f"No structured JSON files found in '{input_structured_dir}'. Adding only dummy papers.")
else:
    print(f"Found {len(json_files)} structured JSON files. Processing...")
    for json_file in json_files:
        full_json_path = os.path.join(input_structured_dir, json_file)
        try:
            with open(full_json_path, "r", encoding="utf-8") as f:
                data = json.load(f)


            title = os.path.splitext(json_file)[0].replace("_", " ")


            paper_dict = {
                "title": title,
                "authors": ["Jane Doe", "John Smith"],
                "year": 2023,
                "journal": "Journal of Research",
                "abstract": data.get("abstract", ""),
                "introduction": data.get("introduction", ""),
                "methods": "Detailed methodology including experimental setup and data collection.", # Placeholder
                "results": "Presented findings from experiments, including statistical analysis and observations.", # Placeholder
                "conclusion": data.get("conclusion", "")
            }
            all_papers_data.append(paper_dict)
            print(f"Added data from '{json_file}'.")

        except Exception as e:
            print(f"Error processing JSON file '{json_file}': {e}")


dummy_paper_1 = {
    "title": "Advanced Techniques in Quantum Computing",
    "authors": ["Alice Johnson", "Bob Williams"],
    "year": 2024,
    "journal": "Quantum Science Review",
    "abstract": "This paper explores novel algorithms for quantum computing, focusing on their efficiency and potential applications in cryptography and drug discovery.",
    "introduction": "Quantum computing promises to revolutionize various fields by offering computational power beyond classical limits. This work introduces an overview of current quantum algorithms and their theoretical underpinnings.",
    "methods": "We employed a superconducting qubit system for experimental validation and simulated larger quantum circuits using tensor network methods.",
    "results": "Our simulations show a 20% increase in computational speed for certain problems compared to existing quantum algorithms. Experimental data confirms stability in small-scale implementations.",
    "conclusion": "The findings suggest that the proposed quantum algorithms could significantly enhance the capabilities of future quantum computers. Further research is needed to scale these methods."
}

dummy_paper_2 = {
    "title": "Impact of Climate Change on Marine Ecosystems",
    "authors": ["Dr. Sarah Chen", "Dr. David Lee"],
    "year": 2023,
    "journal": "Environmental Ecology",
    "abstract": "This study investigates the profound effects of rising ocean temperatures and acidification on various marine ecosystems, with a focus on coral reefs and polar regions.",
    "introduction": "Climate change poses an unprecedented threat to global biodiversity, with marine environments being particularly vulnerable. Understanding these impacts is crucial for conservation efforts.",
    "methods": "Long-term observational data, satellite imagery, and controlled laboratory experiments were used to assess changes in species distribution, coral bleaching, and ocean pH levels.",
    "results": "We observed a significant decline in coral coverage and a northward shift in several marine species. Ocean acidification rates exceeded predictions, indicating rapid environmental stress.",
    "conclusion": "The escalating impacts of climate change demand urgent and coordinated global action to mitigate further damage to marine ecosystems. Policy changes and conservation strategies are paramount."
}


all_papers_data.append(dummy_paper_1)
all_papers_data.append(dummy_paper_2)

print(f"\nTotal {len(all_papers_data)} papers (including dummy papers) collected.")
print("First 2 entries of all_papers_data:")
for i, paper in enumerate(all_papers_data[:2]):
    print(f"  Paper {i+1}: {paper['title']} (Year: {paper['year']})")

import os
import json
import re


all_papers_data = []


input_structured_dir = "data/structured_sections"


output_comparisons_dir = "data/comparisons"
os.makedirs(output_comparisons_dir, exist_ok=True)


os.makedirs(input_structured_dir, exist_ok=True)


json_files = [f for f in os.listdir(input_structured_dir) if f.lower().endswith('.json')]

if not json_files:
    print(f"No structured JSON files found in '{input_structured_dir}'. Adding only dummy papers.")
else:
    print(f"Found {len(json_files)} structured JSON files. Processing...")
    for json_file in json_files:
        full_json_path = os.path.join(input_structured_dir, json_file)
        try:
            with open(full_json_path, "r", encoding="utf-8") as f:
                data = json.load(f)


            title = os.path.splitext(json_file)[0].replace("_", " ")


            paper_dict = {
                "title": title,
                "authors": ["Jane Doe", "John Smith"],
                "year": 2023,
                "journal": "Journal of Research",
                "abstract": data.get("abstract", ""),
                "introduction": data.get("introduction", ""),
                "methods": "Detailed methodology including experimental setup and data collection.", # Placeholder
                "results": "Presented findings from experiments, including statistical analysis and observations.", # Placeholder
                "conclusion": data.get("conclusion", "")
            }
            all_papers_data.append(paper_dict)
            print(f"Added data from '{json_file}'.")

        except Exception as e:
            print(f"Error processing JSON file '{json_file}': {e}")


dummy_paper_1 = {
    "title": "Advanced Techniques in Quantum Computing",
    "authors": ["Alice Johnson", "Bob Williams"],
    "year": 2024,
    "journal": "Quantum Science Review",
    "abstract": "This paper explores novel algorithms for quantum computing, focusing on their efficiency and potential applications in cryptography and drug discovery.",
    "introduction": "Quantum computing promises to revolutionize various fields by offering computational power beyond classical limits. This work introduces an overview of current quantum algorithms and their theoretical underpinnings.",
    "methods": "We employed a superconducting qubit system for experimental validation and simulated larger quantum circuits using tensor network methods.",
    "results": "Our simulations show a 20% increase in computational speed for certain problems compared to existing quantum algorithms. Experimental data confirms stability in small-scale implementations.",
    "conclusion": "The findings suggest that the proposed quantum algorithms could significantly enhance the capabilities of future quantum computers. Further research is needed to scale these methods."
}

dummy_paper_2 = {
    "title": "Impact of Climate Change on Marine Ecosystems",
    "authors": ["Dr. Sarah Chen", "Dr. David Lee"],
    "year": 2023,
    "journal": "Environmental Ecology",
    "abstract": "This study investigates the profound effects of rising ocean temperatures and acidification on various marine ecosystems, with a focus on coral reefs and polar regions.",
    "introduction": "Climate change poses an unprecedented threat to global biodiversity, with marine environments being particularly vulnerable. Understanding these impacts is crucial for conservation efforts.",
    "methods": "Long-term observational data, satellite imagery, and controlled laboratory experiments were used to assess changes in species distribution, coral bleaching, and ocean pH levels.",
    "results": "We observed a significant decline in coral coverage and a northward shift in several marine species. Ocean acidification rates exceeded predictions, indicating rapid environmental stress.",
    "conclusion": "The escalating impacts of climate change demand urgent and coordinated global action to mitigate further damage to marine ecosystems. Policy changes and conservation strategies are paramount."
}


all_papers_data.append(dummy_paper_1)
all_papers_data.append(dummy_paper_2)

print(f"\nTotal {len(all_papers_data)} papers (including dummy papers) collected.")
print("First 2 entries of all_papers_data:")
for i, paper in enumerate(all_papers_data[:2]):
    print(f"  Paper {i+1}: {paper['title']} (Year: {paper['year']})")

"""## Implement APA Reference Generator

"""

import re

def generate_apa_reference(paper):
    """
    Generates an APA 7th edition style reference string for a given paper.
    Handles author formatting, title casing, and journal italicization.
    """
    authors = paper.get("authors", [])
    year = paper.get("year")
    title = paper.get("title")
    journal = paper.get("journal")


    author_str = ""
    if authors:
        if len(authors) > 7:

            formatted_authors = []
            for i, author in enumerate(authors[:6]):
                parts = author.split()
                last_name = parts[-1]
                initials = ". ".join([p[0] for p in parts[:-1] if p]) + "."
                formatted_authors.append(f"{last_name}, {initials}")

            last_author_parts = authors[-1].split()
            last_author_last_name = last_author_parts[-1]
            last_author_initials = ". ".join([p[0] for p in last_author_parts[:-1] if p]) + "."

            author_str = f"{', '.join(formatted_authors)}, ... {last_author_last_name}, {last_author_initials}"
        else:

            formatted_authors = []
            for i, author in enumerate(authors):
                parts = author.split()
                last_name = parts[-1]
                initials = ". ".join([p[0] for p in parts[:-1] if p]) + "."
                formatted_authors.append(f"{last_name}, {initials}")

            if len(formatted_authors) > 1:
                author_str = f"{', '.join(formatted_authors[:-1])}, & {formatted_authors[-1]}"
            else:
                author_str = formatted_authors[0]


    year_str = f"({year})." if year else "(n.d.)."



    def to_sentence_case(text):
        if not text: return ""
        text = text.lower()
        text = text[0].upper() + text[1:]
        text = re.sub(r':\s*([a-z])', lambda pat: ': ' + pat.group(1).upper(), text)
        return text

    title_str = to_sentence_case(title) + "."


    journal_str = f"<i>{journal}</i>." if journal else ""


    apa_reference = f"{author_str} {year_str} {title_str} {journal_str}"
    return apa_reference.strip()



print("\n--- APA References for Sample Papers ---")
for i, paper in enumerate(all_papers_data):
    apa_ref = generate_apa_reference(paper)
    print(f"{i+1}. {apa_ref}")

"""## Implement Abstract Draft Generator


"""

def generate_abstract_draft(all_papers_data):
    """
    Generates a synthetic abstract draft by extracting research problems, approaches,
    and key findings from a list of paper dictionaries.
    """
    research_problems = []
    approaches_used = []
    key_findings = []

    for paper in all_papers_data:

        problem_text = paper.get('abstract') or paper.get('introduction', '')
        if problem_text:

            sentences = problem_text.split('.')
            research_problems.append('. '.join(sentences[:2]).strip() + '.')


        method_text = paper.get('methods', '')
        if method_text:

            sentences = method_text.split('.')
            approaches_used.append('. '.join(sentences[:2]).strip() + '.')


        findings_text = paper.get('results') or paper.get('conclusion', '')
        if findings_text:

            sentences = findings_text.split('.')
            key_findings.append('. '.join(sentences[:2]).strip() + '.')


    abstract_draft = f"This review investigates various {', '.join(set(research_problems))} " \
                     f"Different {', '.join(set(approaches_used))} were employed across studies. " \
                     f"Key findings reveal {', '.join(set(key_findings))}"

    return abstract_draft


print("\n--- Generated Abstract Draft ---")
final_abstract_draft = generate_abstract_draft(all_papers_data)
print(final_abstract_draft)

"""## Implement Methods Draft Generator



"""

def generate_methods_draft(all_papers_data):
    """
    Generates a methods section draft for the overall review based on the provided papers.
    """

    num_papers_analyzed = len(all_papers_data)


    analysis_technique = 'comparative analysis, thematic extraction, and narrative synthesis'


    ai_nlp_method = 'prompt-based natural language generation simulating a large language model\'s capabilities'


    methods_draft = (
        f"This review analyzed {num_papers_analyzed} research papers. "
        f"The primary analysis technique involved {analysis_technique} to identify common themes, "
        f"approaches, and findings across the selected literature. "
        f"The synthesis of information and generation of structured outputs was performed "
        f"using {ai_nlp_method}."
    )

    return methods_draft


print("\n--- Generated Methods Draft ---")
final_methods_draft = generate_methods_draft(all_papers_data)
print(final_methods_draft)

"""## Implement Results Draft Generator

"""

def generate_results_draft(all_papers_data):
    """
    Generates a comprehensive results section draft by identifying key trends, similarities,
    differences, and a final synthesized outcome from a list of paper dictionaries.
    """
    extracted_results = []
    extracted_methods = []

    for paper in all_papers_data:

        results_text = paper.get('results') or paper.get('conclusion', '')
        if results_text:
            sentences = results_text.split('.')

            extracted_results.append('. '.join(sentences[:2]).strip() + ('.' if sentences[0].strip() else ''))


        method_text = paper.get('methods', '')
        if method_text:
            sentences = method_text.split('.')

            extracted_methods.append('. '.join(sentences[:2]).strip() + ('.' if sentences[0].strip() else ''))


    key_trends_unique = list(set([t for t in extracted_results if t]))
    key_trends_str = "Key trends observed across the analyzed papers indicate "
    if key_trends_unique:
        key_trends_str += f"{'; '.join(key_trends_unique)}"
    else:
        key_trends_str += "a variety of findings without a clearly dominant trend."


    similarities_differences_str = "The studies employed diverse methodologies, with some overlap in computational or observational approaches. "
    if len(all_papers_data) > 1 and len(set(extracted_methods)) > 1:
        similarities_differences_str += "While some papers utilized experimental validation, others focused on simulated environments or long-term data analysis."
    else:
        similarities_differences_str += "All papers seemed to follow a broadly similar research approach."


    final_outcome_str = (
        "Overall, the synthesis of these papers highlights the rapid advancements in their respective fields, "
        "underscoring the importance of innovative techniques and the critical need for continued research "
        "to address complex global challenges."
    )


    results_draft = (
        f"### Results\n\n"
        f"{key_trends_str}\n\n"
        f"{similarities_differences_str}\n\n"
        f"{final_outcome_str}"
    )

    return results_draft


print("\n--- Generated Results Draft ---")
final_results_draft = generate_results_draft(all_papers_data)
print(final_results_draft)

"""## Orchestrate and Generate Output


"""

import textwrap


final_abstract_draft = generate_abstract_draft(all_papers_data)


final_methods_draft = generate_methods_draft(all_papers_data)


final_results_draft = generate_results_draft(all_papers_data)


apa_reference_list = []


for paper in all_papers_data:
    apa_ref = generate_apa_reference(paper)
    apa_reference_list.append(apa_ref)


print(
    """--- Generated Research Review ---

"""
)


print(
    """### Abstract

"""
)
print(textwrap.fill(final_abstract_draft, width=100))
print("\n")


print(
    """### Methods

"""
)
print(textwrap.fill(final_methods_draft, width=100))
print("\n")

print(
    """### Results

"""
)
print(textwrap.fill(final_results_draft, width=100))
print("\n")


print(
    """### APA References

"""
)
for i, ref in enumerate(apa_reference_list):
    print(f"{i+1}. {textwrap.fill(ref, width=95, subsequent_indent='    ')}")

"""## Add Optional Evaluation Metrics


"""

def evaluate_section_length(section_text, min_length, section_name):
    """
    Evaluates if a section's text meets a minimum character length.
    """
    text_length = len(section_text.strip())
    if text_length >= min_length:
        return f"✅ {section_name} length ({text_length} chars) meets the minimum requirement of {min_length} chars."
    else:
        return f"❌ {section_name} length ({text_length} chars) is below the minimum requirement of {min_length} chars."

print("Defined `evaluate_section_length` function.")

def evaluate_keyword_presence(text, keywords, section_name):
    """
    Evaluates if specified keywords are present in a given text string.
    """
    missing_keywords = []
    present_keywords = []
    text_lower = text.lower()

    for keyword in keywords:
        if keyword.lower() in text_lower:
            present_keywords.append(keyword)
        else:
            missing_keywords.append(keyword)

    if not missing_keywords:
        return f"✅ All required keywords ({', '.join(present_keywords)}) are present in {section_name}."
    elif not present_keywords:
        return f"❌ None of the required keywords ({', '.join(keywords)}) were found in {section_name}."
    else:
        return f"⚠️ In {section_name}: Present keywords: {', '.join(present_keywords)}. Missing keywords: {', '.join(missing_keywords)}."

print("Defined `evaluate_keyword_presence` function.")

print("\n--- Evaluation Results ---")


print("\nAbstract Evaluation:")
print(evaluate_section_length(final_abstract_draft, 150, "Abstract"))
print(evaluate_keyword_presence(final_abstract_draft, ['problem', 'approach', 'findings'], "Abstract"))


print("\nMethods Evaluation:")
print(evaluate_section_length(final_methods_draft, 100, "Methods"))

print("\nResults Evaluation:")
print(evaluate_section_length(final_results_draft, 150, "Results"))

import random

def critical_review(section_text, section_name):
    """
    Simulates a critical review for a given text section, identifying mock weaknesses
    and suggesting revisions.
    """
    weaknesses = []
    revision_suggestions = []


    if len(section_text) < 100:
        weaknesses.append("The content is too brief.")
        revision_suggestions.append("Elaborate further on key points to add depth.")

    if "abstract" in section_name.lower():
        weaknesses.append("Lack of specific methodology mentioned in the abstract.")
        revision_suggestions.append("Include a sentence about the primary method used.")
    elif "introduction" in section_name.lower():
        weaknesses.append("The problem statement could be clearer.")
        revision_suggestions.append("Rephrase the problem to be more explicit and impactful.")
    elif "conclusion" in section_name.lower():
        weaknesses.append("Future work suggestions are too vague.")
        revision_suggestions.append("Provide concrete examples for future research directions.")
    else:
        # Generic suggestions if no specific section match
        if random.random() < 0.5:
            weaknesses.append("Unclear phrasing in some sentences.")
            revision_suggestions.append("Simplify complex sentences for better readability.")
        if random.random() < 0.5:
            weaknesses.append("Could benefit from more specific examples.")
            revision_suggestions.append("Integrate one or two concrete examples to illustrate points.")

    if not weaknesses:
        weaknesses.append("No obvious critical weaknesses identified.")
        revision_suggestions.append("Maintain current quality and clarity.")

    return {
        "weaknesses": weaknesses,
        "revision_suggestions": revision_suggestions
    }

def apply_revisions(original_text, revision_suggestions):
    """
    Simulates applying revision suggestions to the original text.
    For simplicity, it prepends a generic statement and slightly modifies the text.
    """
    if not original_text.strip():
        return "[Revised Content Placeholder: Original text was empty.]"


    revised_text = "[Revised for clarity and completeness] " + original_text


    if "elaborate further" in " ".join(revision_suggestions).lower() and len(original_text) < 200:
        revised_text += " This section has been expanded to provide more detail and context as suggested."
    elif "simplify complex sentences" in " ".join(revision_suggestions).lower():

        revised_text = revised_text.replace("consequently", "so").replace("furthermore", "also")

    return revised_text.strip()

def evaluate_text_quality(text, section_name):
    """
    Simulates a quality evaluation by returning a mock 'quality_score' and 'justification'.
    """
    quality_score = random.randint(5, 10)
    justification = ""

    if len(text) < 50:
        quality_score = random.randint(1, 4)
        justification = "The text is too brief and lacks sufficient detail for a comprehensive assessment."
    elif quality_score >= 8:
        justification = "The text is exceptionally clear, concise, and provides thorough information relevant to the section."
    elif quality_score >= 6:
        justification = "The text is generally well-structured and conveys information effectively, though minor improvements could enhance clarity."
    else:
        justification = "The text requires significant revision to improve clarity, completeness, and adherence to expected content standards."

    return {
        "quality_score": quality_score,
        "justification": justification
    }

print("Defined `critical_review`, `apply_revisions`, and `evaluate_text_quality` functions.")

import os
import json
import re
import nltk
import random

# Ensure nltk punkt tokenizer is available, required by generate_abstract_draft and generate_results_draft
try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt', quiet=True)

# Also explicitly download 'punkt_tab' if it's the one causing issues
try:
    nltk.data.find('tokenizers/punkt_tab')
except LookupError:
    nltk.download('punkt_tab', quiet=True)


# --- Start of all_papers_data initialization (from cell 5c47a198) ---
all_papers_data = []
input_structured_dir = "data/structured_sections"
output_comparisons_dir = "data/comparisons"
os.makedirs(output_comparisons_dir, exist_ok=True)
os.makedirs(input_structured_dir, exist_ok=True)

json_files = [f for f in os.listdir(input_structured_dir) if f.lower().endswith('.json')]

if not json_files:
    print(f"No structured JSON files found in '{input_structured_dir}'. Adding only dummy papers.")
else:
    print(f"Found {len(json_files)} structured JSON files. Processing...")
    for json_file in json_files:
        full_json_path = os.path.join(input_structured_dir, json_file)
        try:
            with open(full_json_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            title = os.path.splitext(json_file)[0].replace("_", " ")
            paper_dict = {
                "title": title,
                "authors": ["Jane Doe", "John Smith"], # Placeholder
                "year": 2023, # Placeholder
                "journal": "Journal of Research", # Placeholder
                "abstract": data.get("abstract", ""),
                "introduction": data.get("introduction", ""),
                "methods": "Detailed methodology including experimental setup and data collection.", # Placeholder
                "results": "Presented findings from experiments, including statistical analysis and observations.", # Placeholder
                "conclusion": data.get("conclusion", "")
            }
            all_papers_data.append(paper_dict)
            print(f"Added data from '{json_file}'.")
        except Exception as e:
            print(f"Error processing JSON file '{json_file}': {e}")

dummy_paper_1 = {
    "title": "Advanced Techniques in Quantum Computing",
    "authors": ["Alice Johnson", "Bob Williams"],
    "year": 2024,
    "journal": "Quantum Science Review",
    "abstract": "This paper explores novel algorithms for quantum computing, focusing on their efficiency and potential applications in cryptography and drug discovery.",
    "introduction": "Quantum computing promises to revolutionize various fields by offering computational power beyond classical limits. This work introduces an overview of current quantum algorithms and their theoretical underpinnings.",
    "methods": "We employed a superconducting qubit system for experimental validation and simulated larger quantum circuits using tensor network methods.",
    "results": "Our simulations show a 20% increase in computational speed for certain problems compared to existing quantum algorithms. Experimental data confirms stability in small-scale implementations.",
    "conclusion": "The findings suggest that the proposed quantum algorithms could significantly enhance the capabilities of future quantum computers. Further research is needed to scale these methods."
}

dummy_paper_2 = {
    "title": "Impact of Climate Change on Marine Ecosystems",
    "authors": ["Dr. Sarah Chen", "Dr. David Lee"],
    "year": 2023,
    "journal": "Environmental Ecology",
    "abstract": "This study investigates the profound effects of rising ocean temperatures and acidification on various marine ecosystems, with a focus on coral reefs and polar regions.",
    "introduction": "Climate change poses an unprecedented threat to global biodiversity, with marine environments being particularly vulnerable. Understanding these impacts is crucial for conservation efforts.",
    "methods": "Long-term observational data, satellite imagery, and controlled laboratory experiments were used to assess changes in species distribution, coral bleaching, and ocean pH levels.",
    "results": "We observed a significant decline in coral coverage and a northward shift in several marine species. Ocean acidification rates exceeded predictions, indicating rapid environmental stress.",
    "conclusion": "The escalating impacts of climate change demand urgent and coordinated global action to mitigate further damage to marine ecosystems. Policy changes and conservation strategies are paramount."
}
all_papers_data.append(dummy_paper_1)
all_papers_data.append(dummy_paper_2)
# --- End of all_papers_data initialization ---


# --- Start of generate_abstract_draft (from cell bff67c77) ---
def generate_abstract_draft(all_papers_data):
    """
    Generates a synthetic abstract draft by extracting research problems, approaches,
    and key findings from a list of paper dictionaries.
    """
    research_problems = []
    approaches_used = []
    key_findings = []

    for paper in all_papers_data:
        problem_text = paper.get('abstract') or paper.get('introduction', '')
        if problem_text:
            sentences = nltk.sent_tokenize(problem_text)
            research_problems.append('. '.join(sentences[:2]).strip() + ('.' if sentences and sentences[0].strip() else ''))

        method_text = paper.get('methods', '')
        if method_text:
            sentences = nltk.sent_tokenize(method_text)
            approaches_used.append('. '.join(sentences[:2]).strip() + ('.' if sentences and sentences[0].strip() else ''))

        findings_text = paper.get('results') or paper.get('conclusion', '')
        if findings_text:
            sentences = nltk.sent_tokenize(findings_text)
            key_findings.append('. '.join(sentences[:2]).strip() + ('.' if sentences and sentences[0].strip() else ''))

    abstract_draft = f"This review investigates various {', '.join(set(research_problems))} " \
                     f"Different {', '.join(set(approaches_used))} were employed across studies. " \
                     f"Key findings reveal {', '.join(set(key_findings))}"
    return abstract_draft
# --- End of generate_abstract_draft ---


# --- Start of generate_methods_draft (from cell 1283690d) ---
def generate_methods_draft(all_papers_data):
    """
    Generates a methods section draft for the overall review based on the provided papers.
    """
    num_papers_analyzed = len(all_papers_data)
    analysis_technique = 'comparative analysis, thematic extraction, and narrative synthesis'
    ai_nlp_method = 'prompt-based natural language generation simulating a large language model\'s capabilities'
    methods_draft = (
        f"This review analyzed {num_papers_analyzed} research papers. "
        f"The primary analysis technique involved {analysis_technique} to identify common themes, "
        f"approaches, and findings across the selected literature. "
        f"The synthesis of information and generation of structured outputs was performed "
        f"using {ai_nlp_method}."
    )
    return methods_draft




def generate_results_draft(all_papers_data):
    """
    Generates a comprehensive results section draft by identifying key trends, similarities,
    differences, and a final synthesized outcome from a list of paper dictionaries.
    """
    extracted_results = []
    extracted_methods = []

    for paper in all_papers_data:
        results_text = paper.get('results') or paper.get('conclusion', '')
        if results_text:
            sentences = nltk.sent_tokenize(results_text)
            extracted_results.append('. '.join(sentences[:2]).strip() + ('.' if sentences and sentences[0].strip() else ''))

        method_text = paper.get('methods', '')
        if method_text:
            sentences = nltk.sent_tokenize(method_text)
            extracted_methods.append('. '.join(sentences[:2]).strip() + ('.' if sentences and sentences[0].strip() else ''))

    key_trends_unique = list(set([t for t in extracted_results if t]))
    key_trends_str = "Key trends observed across the analyzed papers indicate "
    if key_trends_unique:
        key_trends_str += f"{'; '.join(key_trends_unique)}"
    else:
        key_trends_str += "a variety of findings without a clearly dominant trend."

    similarities_differences_str = "The studies employed diverse methodologies, with some overlap in computational or observational approaches. "
    if len(all_papers_data) > 1 and len(set(extracted_methods)) > 1:
        similarities_differences_str += "While some papers utilized experimental validation, others focused on simulated environments or long-term data analysis."
    else:
        similarities_differences_str += "All papers seemed to follow a broadly similar research approach."

    final_outcome_str = (
        "Overall, the synthesis of these papers highlights the rapid advancements in their respective fields, "
        "underscoring the importance of innovative techniques and the critical need for continued research "
        "to address complex global challenges."
    )
    results_draft = (
        f"### Results\n\n"
        f"{key_trends_str}\n\n"
        f"{similarities_differences_str}\n\n"
        f"{final_outcome_str}"
    )
    return results_draft
# --- End of generate_results_draft ---


# --- Start of critical_review, apply_revisions, evaluate_text_quality (from cell 34377a94) ---
def critical_review(section_text, section_name):
    """
    Simulates a critical review for a given text section, identifying mock weaknesses
    and suggesting revisions.
    """
    weaknesses = []
    revision_suggestions = []

    # Simulate some weaknesses and suggestions based on section name or text length
    if len(section_text) < 100:
        weaknesses.append("The content is too brief.")
        revision_suggestions.append("Elaborate further on key points to add depth.")

    if "abstract" in section_name.lower():
        weaknesses.append("Lack of specific methodology mentioned in the abstract.")
        revision_suggestions.append("Include a sentence about the primary method used.")
    elif "introduction" in section_name.lower():
        weaknesses.append("The problem statement could be clearer.")
        revision_suggestions.append("Rephrase the problem to be more explicit and impactful.")
    elif "conclusion" in section_name.lower():
        weaknesses.append("Future work suggestions are too vague.")
        revision_suggestions.append("Provide concrete examples for future research directions.")
    else:

        if random.random() < 0.5:
            weaknesses.append("Unclear phrasing in some sentences.")
            revision_suggestions.append("Simplify complex sentences for better readability.")
        if random.random() < 0.5:
            weaknesses.append("Could benefit from more specific examples.")
            revision_suggestions.append("Integrate one or two concrete examples to illustrate points.")

    if not weaknesses:
        weaknesses.append("No obvious critical weaknesses identified.")
        revision_suggestions.append("Maintain current quality and clarity.")

    return {
        "weaknesses": weaknesses,
        "revision_suggestions": revision_suggestions
    }

def apply_revisions(original_text, revision_suggestions):
    """
    Simulates applying revision suggestions to the original text.
    For simplicity, it prepends a generic statement and slightly modifies the text.
    """
    if not original_text.strip():
        return "[Revised Content Placeholder: Original text was empty.]"


    revised_text = "[Revised for clarity and completeness] " + original_text


    if "elaborate further" in " ".join(revision_suggestions).lower() and len(original_text) < 200:
        revised_text += " This section has been expanded to provide more detail and context as suggested."
    elif "simplify complex sentences" in " ".join(revision_suggestions).lower():

        revised_text = revised_text.replace("consequently", "so").replace("furthermore", "also")

    return revised_text.strip()

def evaluate_text_quality(text, section_name):
    """
    Simulates a quality evaluation by returning a mock 'quality_score' and 'justification'.
    """
    quality_score = random.randint(5, 10)
    justification = ""

    if len(text) < 50:
        quality_score = random.randint(1, 4)
        justification = "The text is too brief and lacks sufficient detail for a comprehensive assessment."
    elif quality_score >= 8:
        justification = "The text is exceptionally clear, concise, and provides thorough information relevant to the section."
    elif quality_score >= 6:
        justification = "The text is generally well-structured and conveys information effectively, though minor improvements could enhance clarity."
    else:
        justification = "The text requires significant revision to improve clarity, completeness, and adherence to expected content standards."

    return {
        "quality_score": quality_score,
        "justification": justification
    }



print("\n--- Processing and Evaluating Draft Sections ---")


final_abstract_draft = generate_abstract_draft(all_papers_data)
final_methods_draft = generate_methods_draft(all_papers_data)
final_results_draft = generate_results_draft(all_papers_data)

def process_section(draft_content, section_name):
    print(f"\n### {section_name} Section")
    print("\nOriginal Draft:")
    print(draft_content)


    review_output = critical_review(draft_content, section_name)
    print("\nCritical Review:")
    print("  Weaknesses:", review_output["weaknesses"])
    print("  Revision Suggestions:", review_output["revision_suggestions"])


    revised_content = apply_revisions(draft_content, review_output["revision_suggestions"])
    print("\nRevised Content:")
    print(revised_content)


    original_evaluation = evaluate_text_quality(draft_content, section_name)
    print("\nOriginal Draft Evaluation:")
    print(f"  Quality Score: {original_evaluation['quality_score']}/10")
    print(f"  Justification: {original_evaluation['justification']}")


    revised_evaluation = evaluate_text_quality(revised_content, section_name)
    print("\nRevised Content Evaluation:")
    print(f"  Quality Score: {revised_evaluation['quality_score']}/10")
    print(f"  Justification: {revised_evaluation['justification']}")


process_section(final_abstract_draft, "Abstract")

process_section(final_methods_draft, "Methods")


process_section(final_results_draft, "Results")